import test_assert from './assert-test.js';
import test_assertDefined from './assert-defined-test.js';
import test_assertEqual from './assert-equal-test.js';
import test_assertFalsy from './assert-falsy-test.js';
import test_assertGTandLT from './assert-greater-and-less-than-test.js';
import test_assertMatches from './assert-matches-test.js';
import test_assertNotEqual from './assert-not-equal-test.js';
import test_assertNotMatches from './assert-not-matches-test.js';
import test_assertUndefined from './assert-undefined-test.js';
import test_doesMatch from './does-match-test.js';
import test_isBoolean from './is-boolean-test.js';
import test_isDate from './is-date-test.js';
import test_isEqual from './is-equal-test.js';
import test_isFunction from './is-function-test.js';
import test_isMap from './is-map-test.js';
import test_isNonEmptyString from './is-non-empty-string-test.js';
import test_isNumber from './is-number-test.js';
import test_isNumberNotNaN from './is-number-not-nan-test.js';
import test_isPlainObject from './is-plain-object-test.js';
import test_isPrimitive from './is-primitive-test.js';
import test_isRegExp from './is-regexp-test.js';
import test_isSet from './is-set-test.js';
import test_isString from './is-string-test.js';
import test_isUndefined from './is-undefined-test.js';
import test_isValidDate from './is-valid-date-test.js';
import test_toFriendlyString from './to-friendly-string-test.js';


test_assert();
test_assertDefined();
test_assertEqual();
test_assertFalsy();
test_assertGTandLT();
test_assertMatches();
test_assertNotEqual();
test_assertNotMatches();
test_assertUndefined();
test_doesMatch();
test_isBoolean();
test_isDate();
test_isEqual();
test_isFunction();
test_isMap();
test_isNonEmptyString();
test_isNumber();
test_isNumberNotNaN();
test_isPlainObject();
test_isPrimitive();
test_isRegExp();
test_isSet();
test_isString();
test_isUndefined();
test_isValidDate();
test_toFriendlyString();
